from pathlib import Path
import json,csv,hashlib,datetime
import numpy as np
import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt
R=Path(__file__).resolve().parent
s=json.loads((R/'SUMMARY_V2.json').read_text());cases=s['cases'];fine=[x for x in cases if x['dt_s']==.5e-6]
windows=['pre_onset_cost','service_cost','recovery_cost','post_deadline_cost','whole_observation_cost','checkpoint_total_cost']
rows=[];diagnostics=[]
for c in cases:
 a=np.load(R/(c['tag']+'_s1.npz'));b=np.load(R/(c['tag']+'_s0.npz'));ad=np.load(R/(c['tag']+'_s1_dense.npz'));bd=np.load(R/(c['tag']+'_s0_dense.npz'));onset=2+c['offset_s'];t=a['t'];m=(t>onset+.2-1e-12)&(t<=onset+.7+1e-12)
 zn={'case':c['tag'],'post_result_accounting_clarification':True,'recovery_all_PWM_boundary_max_abs_dZ_J':float(np.max(abs(a['filter_energy'][m]-b['filter_energy'][m]))),'final100ms_dense_max_abs_dZ_J':float(np.max(abs(ad['filter_energy']-bd['filter_energy']))),'deadline_dZ_J':c['snapshots']['deadline']['difference']['filter_energy'],'final_observation_dZ_J':c['snapshots']['post_observation']['difference']['filter_energy'],'return_tolerance_implied_dZ_bound_J':.0003*np.sqrt(1.5)*1500*np.sqrt(3)*2,'all_recovery_window_dZ_sampling':'100 us phase-matched PWM boundaries; final100ms additionally fixed1us grid; no continuous-time extremum claim'}
 diagnostics.append(zn)
 endpoints={'pre_onset_cost':(None,'onset'),'service_cost':('onset','service_end'),'recovery_cost':('service_end','deadline'),'post_deadline_cost':('deadline','post_observation'),'whole_observation_cost':('onset','post_observation'),'checkpoint_total_cost':(None,'post_observation')}
 for w in windows:
  st,en=endpoints[w];r={'case':c['tag'],'evidence_group':c.get('evidence_group','nominal'),'window':w,**c[w]}
  for key in ['W','B','filter_energy']:
   r['incremental_change_'+key+'_J']=c['snapshots'][en]['difference'][key]-(c['snapshots'][st]['difference'][key] if st else 0)
  rows.append(r)
(R/'FILTER_ENERGY_ACCOUNTING.json').write_text(json.dumps({'clarified_after_initial_V2_results':True,'identity':'d(W+B)/dt=Pgrid-R*sum(i^2)-d-dZ/dt; Z=L*sum(i^2)/2','only_battery_transfer_cancels':True,'controller_measured_quantity':'S=W+B, capacitor-plus-inventory energy','measurement_model':'Noiseless ideal instantaneous W/B sensing at10kHz PWM starts; no added filtering or delay; numerical integration error is not a sensor-accuracy claim','derived_return_bound':'|ΔZ|≤(L/2)(||is||2+||ih||2)||is-ih||2≤L sqrt(3/2)1500 sqrt(3)2 =1.909188J, using both branch1500A space-vector bounds and each paired phase≤2A','cases':diagnostics},indent=2)+'\n')
fields=list(dict.fromkeys(k for r in rows for k in r));
with (R/'ENERGY_COST_TABLE_V2.csv').open('w') as f:
 wr=csv.DictWriter(f,fieldnames=fields);wr.writeheader();wr.writerows(rows)
with (R/'ACCEPTANCE_TABLE_V2.csv').open('w') as f:
 fields=['case','group','tau_ms','ramp_MW_per_s','onset_us','dt_us','hard_bounds','tracking','physical_return','budget','full_pass','dW_J','dB_J','dI_A','recovery_net_J','recovery_positive_J','recovery_absolute_J','max_incremental_cP_W']
 wr=csv.DictWriter(f,fieldnames=fields);wr.writeheader()
 for c in cases:
  d=c['last_100ms_dense_max_abs_differences'];k=c['recovery_cost'];wr.writerow(dict(case=c['tag'],group=c.get('evidence_group','nominal'),tau_ms=c['actual_tau_s']*1000,ramp_MW_per_s=c['actual_ramp_W_per_s']/1e6,onset_us=c['offset_s']*1e6,dt_us=c['dt_s']*1e6,hard_bounds=c['physical_all_pass'],tracking=c['tracking']['pass'],physical_return=c['physical_recovery_pass'],budget=c['budget_pass'],full_pass=c['pass'],dW_J=d['W'],dB_J=d['B'],dI_A=max(d[a] for a in ['ia','ib','ic']),recovery_net_J=k['signed_incremental_grid_J'],recovery_positive_J=k['positive_incremental_grid_J'],recovery_absolute_J=k['absolute_integral_incremental_grid_J'],max_incremental_cP_W=k['max_abs_incremental_cP_W']))
# Figure emphasizes the retained failure and the separately frozen repair on identical known regression.
fig,ax=plt.subplots(3,1,figsize=(9,8),sharex=True);tag='tau4_r25_o37_h05'
for root,label,col in [(R.parent,'V1A capacitor-only PI, retained failure','tab:red'),(R,'V2 capacitor+inventory PI','tab:blue')]:
 a=np.load(root/(tag+'_s1.npz'));b=np.load(root/(tag+'_s0.npz'));t=a['t']-2.000037;m=t>=.2
 for aa,k in zip(ax,['cp','W','B']):aa.plot(t[m],(a[k]-b[k])[m],label=label,color=col,lw=1.4)
for aa in ax:aa.axvspan(.6,.7,color='green',alpha=.08);aa.axvline(.7,color='green',ls='--');aa.grid(alpha=.25)
ax[0].axhline(-5000,color='black',ls=':',label='Frozen paired cP limit');ax[0].set_ylabel('Incremental cP (W)');ax[0].legend(fontsize=8);ax[1].set_ylabel('Paired W difference (J)');ax[2].set_ylabel('Paired B difference (J)');ax[2].set_xlabel('Time since declared onset (s)');fig.suptitle('Known regression: internal battery transfer need not be counteracted by the grid');fig.tight_layout();fig.savefig(R/'V1A_V2_REGRESSION_COMPARISON.png',dpi=170);plt.close(fig)
fig,ax=plt.subplots(2,1,figsize=(10,7),sharex=True)
for c in fine:
 if c.get('evidence_group')!='confirmation':continue
 a=np.load(R/(c['tag']+'_s1.npz'));b=np.load(R/(c['tag']+'_s0.npz'));t=a['t']-(2+c['offset_s']);m=t>=.2;label=c['tag'].replace('_h05','')
 ax[0].plot(t[m],(a['W']-b['W'])[m],label=label,lw=1);ax[1].plot(t[m],(a['cp']-b['cp'])[m],lw=1)
for aa in ax:aa.axvspan(.6,.7,color='green',alpha=.08);aa.axvline(.7,color='green',ls='--');aa.grid(alpha=.25)
ax[0].legend(ncol=2,fontsize=8);ax[0].set_ylabel('Paired W difference (J)');ax[1].set_ylabel('Incremental cP (W)');ax[1].set_xlabel('Time since declared onset (s)');fig.suptitle('V2 fresh confirmation cells, fine integration step');fig.tight_layout();fig.savefig(R/'FRESH_CONFIRMATION_V2.png',dpi=170);plt.close(fig)
mx=lambda f:max(f(c) for c in cases)
report=['# G3 recovery phase2 V2: causal capacitor-plus-inventory recovery','', '## Outcome',f"{sum(c['pass'] for c in cases)}/{len(cases)} runs satisfy every frozen V2 contract component: two nominal runs, sixteen known-regression runs and sixteen fresh-confirmation runs. This is finite numerical evidence for the enumerated cells, not uniform parameter robustness, hardware validation, exact continuous-time recovery or the original exact-service contract.",'','## Versioned evidence and causal controller','V1A is preserved with14 passes and4 failures. Its four failures were the5kW paired incremental command budget at actualtau4ms/slew25MW/s. V2 is a separate authorized revision, frozen before its own results, and never tuned after its fresh confirmation. The V2 freeze preceded a later request to clarify filter-energy accounting; that later clarification did not change controller, thresholds or results.','',
'At each10kHz PWM boundary, eS=71600−(W+B) J, cP=clip(100eS+2500zS,±4500W), and zS is conditionally integrated by Ts eS with the same antiwindup rule. Inventory control is uB=clip(20(B−50000),±10000W). W/B measurements are ideal, noiseless, instantaneous sampled values; there is no added measurement filter or delay. The legacy source column zw stores zS in this version. Current PI/PWM, original command polynomial, physical plant and all service-clock rules are unchanged.','',
'The loop regulates capacitor-plus-inventory energy S=W+B, not full physical energy. With Z=LΣi²/2, Sdot=Pgrid−RΣi²−d−Zdot. Only the internal battery transfer b cancels. Zdot remains an explicit disturbance; Z is separately evaluated from actual measured currents and is never merged into copper loss.','',
'At service, cP/zS are held and uB=0, preserving the original port feedforward. At recovery, the same causal feedback resumes against constant setpoints. The continuing workload remains650kW afterward, with its original prescribed positive service-time schedule unchanged. No load shedding, no state reset, no future actual workload and no online matched-health trajectory are used. Actual tau/ramp enter only the plant.','',
'Exactly one fresh2s nominal healthy checkpoint per integration resolution initializes every corresponding V2 case. It includes plant, current PI, energy PI, held correction and PWM/grid timing. Healthy and service branches use the same gates and clocks; the healthy branch removes service P/Q/d/u feedforward only. The known midpoint P/Q predictor can act just before an off-PWM onset; pre-onset state and energy are separately recorded and whole cost starts at the common2s checkpoint. Onset states are not asserted identical for19us or37us.','',
'## Frozen scope and numerical acceptance','- Nominal: actualtau5ms/slew30MW/s/onset0, integrationsteps1us and0.5us','- Known regression: actualtau4/6ms × slew25/35MW/s × onset37/73us, each at both steps; these cells were already seen inV1A','- Fresh confirmation: actualtau4.5/5.5ms × slew27/33MW/s × onset19/61us, each at both steps; frozen before anyV2 execution','- Hardware: voltage1080–1320V, each phase and space-vector current≤1500A, B0–100kJ, |b|/|u|≤450kW, declared actual slew, and PWM feasibility','- Service: actual and nominal command means computed over identical20ms bins; |P error|≤2kW and |Q error|≤10kvar','- Physical return: over the final five20ms cycles endingT+0.5s, common1us sampled |ΔW|/|ΔB|≤2J and each |Δi|≤2A','- Recovery budget: paired incremental |cP|≤5kW; |signed|, positive-only and absolute-integral incremental grid energies each≤100J fromT toT+0.5s; an additional0.2s continuing observation exposes downstream debt','- The100J V2 recovery budgets differ from the core100J net late-P allowance during the exact0–0.2s averaged contract; equal units/values do not make the contracts equivalent','',
'## Fine-step results','', '| Cell | evidence | max ΔW J | max ΔB J | max Δi A | max incremental cP W | signed recovery J | positive J | absolute J | full pass |','|---|---|---:|---:|---:|---:|---:|---:|---:|---|']
for c in fine:
 d=c['last_100ms_dense_max_abs_differences'];k=c['recovery_cost'];report.append(f"| {c['tag']} | {c.get('evidence_group','nominal')} | {d['W']:.6g} | {d['B']:.6g} | {max(d[a] for a in ['ia','ib','ic']):.6g} | {k['max_abs_incremental_cP_W']:.6g} | {k['signed_incremental_grid_J']:.6g} | {k['positive_incremental_grid_J']:.6g} | {k['absolute_integral_incremental_grid_J']:.6g} | {c['pass']} |")
report += ['',f"Worst across all{len(cases)} runs: |ΔW|={mx(lambda c:c['last_100ms_dense_max_abs_differences']['W']):.6g}J, |ΔB|={mx(lambda c:c['last_100ms_dense_max_abs_differences']['B']):.6g}J, phase-current difference={mx(lambda c:max(c['last_100ms_dense_max_abs_differences'][a] for a in ['ia','ib','ic'])):.6g}A, paired incremental cP={mx(lambda c:c['recovery_cost']['max_abs_incremental_cP_W']):.6g}W, signed-energy magnitude={mx(lambda c:c['recovery_cost']['absolute_net_incremental_grid_J']):.6g}J, positive energy={mx(lambda c:c['recovery_cost']['positive_incremental_grid_J']):.6g}J and absolute recovery energy={mx(lambda c:c['recovery_cost']['absolute_integral_incremental_grid_J']):.6g}J.",
 f"Hardware extrema across all runs: V={min(c['extrema']['all']['Vmin'] for c in cases):.6f}–{mx(lambda c:c['extrema']['all']['Vmax']):.6f}V, peak phase current={mx(lambda c:c['extrema']['all']['Iphase']):.6f}A, space-vector current={mx(lambda c:c['extrema']['all']['Ispace']):.6f}A. Maximum20ms P/Q errors={mx(lambda c:c['tracking']['P']):.6f}W/{mx(lambda c:c['tracking']['Q']):.6f}var.",'',
'## Filter-energy accounting and justified bound','FILTER_ENERGY_ACCOUNTING.json records exact matched ΔZ at the deadline/final observation, maximum phase-matched ΔZ over every PWM boundary in recovery, and dense1us ΔZ over the final100ms. ENERGY_COST_TABLE_V2.csv gives separate incremental ΔW, ΔB and ΔZ for every window. These are post-result disclosure clarifications; no pass criterion changed.','',
'Given both branch space-vector amplitudes≤1500A, ||i||₂≤√(3/2)1500. If each paired phase current differs by≤2A, ||δi||₂≤√3·2. Therefore |ΔZ|≤(L/2)(||is||₂+||ih||₂)||δi||₂≤1.909188J for L=0.3mH. This bounds filter-energy mismatch implied by the engineering current tolerance; actual observed ΔZ is independently computed, not replaced by that bound.',
 f"Observed maximum recovery-window PWM-boundary |ΔZ|={max(a['recovery_all_PWM_boundary_max_abs_dZ_J'] for a in diagnostics):.6g}J, final100ms dense |ΔZ|={max(a['final100ms_dense_max_abs_dZ_J'] for a in diagnostics):.6g}J, and exact-deadline |ΔZ|={max(abs(a['deadline_dZ_J']) for a in diagnostics):.6g}J. No continuous-time unsampled extremum guarantee is inferred.",'',
'## Health, energy and costs','The common-clock no-service identity test is bitwise equal. Both nominal warmups and each final healthy comparison satisfy the0.1J/0.2A successive-cycle qualification. The healthy bias learned before service is about52.4W in cP on average and45.1W at the held phase, while actual continuing grid increment vs model baseline is about1.14W. The command bias compensates sampled tracking, not52W of extra physical load.','',
'ENERGY_COST_TABLE_V2.csv includes all nominal/regression/confirmation cells at both steps for checkpoint→onset, service, recovery, post-deadline, onset→final and checkpoint→final. It reports gross AC and net-after-copper increments vs matched health AND the theoretical model baseline, plus absolute and positive-only cost. Signed energies use physical quadrature/snapshots; absolute/positive metrics use matched PWM-cycle average power, not instantaneous switched-power absolute integrals. The model baseline gross P is654498.72485653043W, copper loss4498.72485653043W, net650000W.','',
'Fine nominal example:', '', '| Window | gross Δ health J | net-after-copper Δ health J | gross Δ model J | net-after-copper Δ model J | positive Δ health J | absolute Δ health J |','|---|---:|---:|---:|---:|---:|---:|']
for w in ['service_cost','recovery_cost','post_deadline_cost','checkpoint_total_cost']:
 k=fine[0][w];report.append(f"| {w} | {k['signed_incremental_grid_J']:.9f} | {k['net_after_copper_increment_vs_healthy_J']:.9f} | {k['signed_grid_vs_model_baseline_J']:.9f} | {k['net_after_copper_increment_vs_model_baseline_J']:.9f} | {k['positive_incremental_grid_J']:.6f} | {k['absolute_integral_incremental_grid_J']:.6f} |")
report += ['',f"Maximum full-trajectory numerical physical-energy closure residual={mx(lambda c:c['extrema']['all']['closure']):.6g}J. Two-step convergence is retained in SUMMARY_V2.json. These residuals check the numerical simulator, not real measurement accuracy. Ideal switches, prescribed balanced grid, known L/R/C, noiseless sampling and the selected tau/ramp uncertainties limit the physical interpretation.",'',
'## Files and reproduction','Authoritative protocol: PROTOCOL_V2.json plus the pre-result LEDGER_ADDENDUM_PRE_RESULT.json. Frozen code/executable hashes: EXECUTION_FREEZE_V2.json. Run warmup, nominal, regression, confirmation in that order with run_campaign.py; run summarize.py then make_report.py. Independent audit lives in the recovery_phase2/audit area. No V1A frozen file or original theory/source/audit/validation/result file is modified by this revision.','',
'Complete controller/inventory/duty residuals are retained as diagnostics; the claim remains finite-window physical recovery to declared tolerances. There is no claim of exact full-state equality, guaranteed return at every intermediate moment, or uniform uncertainty robustness.']
(R/'REPORT_V2.md').write_text('\n'.join(report)+'\n')
print('Created report, full ledgers, acceptance and filter-energy diagnostics, figures')
