"""Human-readable interpretation of the original finite nonlinear replay audit."""
from pathlib import Path
import json,hashlib
P=Path(__file__).resolve().parent;d=json.loads((P/'NONLINEAR_AUDIT.json').read_text());c=json.loads((P/'NONLINEAR_FREEZE.json').read_text())
lines=['# G6 unchanged-workpoint nonlinear stress replays','',f"Status: {d['completed_replays']}/{d['expected_replays']} pre-frozen runs exported; complete={d['complete']}.",'','## Scope first','','Both supplemental constant-P ports have P0=0 at the original qualified operating points. These are signed-injection stress replays. Negative probe power occurs in each nonzero waveform. Native aggregate bus loads remain a separate impedance-load background; their nonnegativity cannot be reinterpreted as a controllable positive-compute load. No throughput calibration, positive compute embedding, full-family nonlinear robustness, infinite-time nonlinear safety, or interval-certified numerical result is claimed.','', 'The official Kundur and WECC source model parameters, original power-flow equilibria, native PQ dynamic conversions, and disabled demonstration events are unchanged. Independently reconstructed x0/y0 match the original stored qualified descriptor x0/y0 exactly. Each run initializes once; electrical state carries across all 65 replayed blocks.','','## Frozen design','','Equal-split ray (0.5,0.5), T=2s, q1=(1,1,-1,-1), q2=(1,-1,-1,1), quarter-block duration 0.5s. For each network: committed inner 0.98 times conservative numerical LTI capacity lower bound; committed outer 1.02 times LTI capacity outer bound; matching two dynamic-optional cases; erroneous reset-inner 0.98 times reset capacity inner bound, driven by the carried-state committed support-achieving word. All choices are fixed in NONLINEAR_FREEZE.json before any nonlinear results.','', 'Every 257-block full word and its 65-block suffix are preserved. The nonlinear replay starts the retained suffix at t=1s, executes all 65 complete blocks through t=131s, then holds input zero through t=151s. It includes the current block past the support target phase, preserving exact blockwise zero incremental energy. Keeping the last 64 past blocks discards only an LTI modal tail with an upper bound smaller than 5e-9Hz at all preselected amplitudes and aligned observation times. This is an LTI truncation statement only; nonlinear full-history equivalence is not asserted.','', 'Nonlinear maximum steps are 1/64s and 1/128s, with every ZOH jump registered and ±1e-4s event bracketing. The selected support time is an explicit observation event. Same-input LTI output uses analytic modal exponentials with exact ZOH event splitting and no electrical resets, evaluated at the nonlinear solver times. Modal transfer qualification and original descriptor/state independent replay are in ../transfer. Floating exponentials and event-resolved numerical integration are not formal exact-real proofs.','','## Refined finite-horizon results','','| Network | Frozen case | Total amplitude MW | Same-input LTI peak Hz | Nonlinear peak Hz | Nonlinear margin to 0.05Hz |','|---|---|---:|---:|---:|---:|']
for r in d['results']:
 if r['dt_s']==1/128:lines.append(f"| {r['network']} | {r['case']} | {r['amplitude_MW']:.8f} | {r['LTI_peak_Hz']:.9f} | {r['nonlinear_peak_Hz']:.9f} | {r['nonlinear_margin_Hz']:+.9f} |")
lines+=['','Positive margin means this finite numerical replay remained inside the chosen research threshold. It is not a safety certificate for all allowed words. Negative margin means an observed finite violating trajectory.','', '## Boundary conclusions','']
for net in c['networks']:
 for label in ['committed_inner','dynamic_optional_inner']:
  rr=[r for r in d['results'] if r['network']==net and r['case']==label]
  if rr:
   r=min(rr,key=lambda a:a['dt_s']);status='FAILED nonlinear transfer: the LTI-inside witness exceeds 0.05Hz' if r['nonlinear_margin_Hz']<0 else 'this selected nonlinear witness stays inside 0.05Hz'
   lines.append(f"- {net} {label}: {status}, peak {r['nonlinear_peak_Hz']:.9f}Hz at maximum step {r['dt_s']:.9f}s")
lines+=['','The cause of any nonlinear mismatch is not assigned to a specific limiter/controller without a separate diagnostic. Step refinement and unchanged source/workpoint/input checks address numerical or input substitutions; they do not remove genuine model nonlinearity.','', '## Refinement and model mismatch','']
for r in d['refinement']:lines.append(f"- {r['name']}: coarse/fine peak change {r['peak_refinement_difference_Hz']:.9g}Hz; support-target change {r['target_refinement_difference_Hz']:.9g}Hz; threshold decision unchanged={r['frequency_threshold_decision_unchanged']}; exact schedule identity={r['same_actual_schedule_both_steps']}")
lines+=['','Per-run outputs report full-trace maximum/RMS LTI-versus-nonlinear errors, selected support values, terminal-ringdown peaks, generator/time attaining the sampled maximum, and native-plus-probe minimum load. These mismatches must not be hidden by reporting only boundary classifications.','','## Evidence files','','- NONLINEAR_FREEZE.json: dated pre-outcome choice and source hashes','- *_input.npz: full and trimmed words plus full/actual event arrays','- *_actual_schedule.csv: actual common-sign, optional-amplitude, Q=0 event schedule','- *_dt64.npz and *_dt128.npz: time grid, actual input, nonlinear all-generator frequencies, identical-input exponential LTI traces, bus voltages, native and total aggregate loads','- *_dt64.json and *_dt128.json: solver completion, operating-point metadata, metrics, physical ledgers','- NONLINEAR_AUDIT.json and NONLINEAR_RESULTS.csv: full numerical audit, blockwise-energy checks, input identity and refinement','- ../transfer/: modal qualification, analytic truncation/phase bounds, and original linear state/descriptor checks','',f"Source-integrity check: all monitored original sources unchanged={d['source_integrity_all_unchanged']}."]
(P/'G6_ORIGINAL_NONLINEAR_REPORT.md').write_text('\n'.join(lines)+'\n')
paths=[P/'run_g6_nonlinear.py',P/'NONLINEAR_FREEZE.json',P/'audit_nonlinear.py',P/'summarize_nonlinear.py'];manifest={str(p.name):{'sha256':hashlib.sha256(p.read_bytes()).hexdigest(),'mtime_utc_epoch':p.stat().st_mtime} for p in paths};(P/'EXECUTION_PROVENANCE.json').write_text(json.dumps({'files':manifest,'note':'Freeze creation precedes all result-file creation. Audit and summary are post-outcome reports; no prospective claim for those scripts.'},indent=2))
