from pathlib import Path
import csv,json,hashlib,datetime,runpy
import numpy as np
P=Path(__file__).resolve().parent
runpy.run_path(str(P/'summarize_positive.py'),run_name='__main__')
s=json.loads((P/'POSITIVE_NONLINEAR_SUMMARY.json').read_text())
assert s['count']==10 and s['all_complete'] and s['all_compute_nonnegative'], 'Wait for all10 frozen cases'
rows=[]
for d in s['results']:
 m=d['metrics'];rows.append({'label':d['label'],'dt_s':d['dt_s'],'total_deltaP_capacity_MW':d['total_amplitude_MW'],'per_port_max_deltaP_MW':d['total_amplitude_MW']/2,'computeP_mean_bus7_MW':50,'computeP_mean_bus8_MW':50,'min_computeP_MW':min(d['min_compute_MW']),'incremental_energy_each_block_MWs':0,'affine_work_each_block':'2*wbar_i','affine_work_full257_blocks':'514*wbar_i','exact_LTI_peak_Hz':m['exact_LTI_peak_Hz'],'sampled_nonlinear_peak_Hz':m['nonlinear_peak_Hz'],'frequency_margin_Hz':m['frequency_limit_margin_Hz'],'finite_case_frequency_status':'below' if m['frequency_limit_margin_Hz']>=0 else 'exceeds','min_busV_pu':m['min_bus_voltage_pu'],'max_busV_pu':m['max_bus_voltage_pu'],'max_NL_LTI_difference_Hz':m['max_NL_LTI_difference_Hz'],'analytic_witness_target_error_Hz':m['analytic_witness_target_error_Hz']})
with (P/'POSITIVE_NONLINEAR_TABLE.csv').open('w') as f:
 w=csv.DictWriter(f,fieldnames=list(rows[0]));w.writeheader();w.writerows(rows)
md=['All10 predeclared original nonlinear replays completed to535s, with actual compute power nonnegative at both ports in every sample and schedule segment. Each forcing word retains all257 complete blocks and the same newly balanced positive initial state.','', '| Case | dt(s) | Total max deviation(MW) | LTI peak(Hz) | Nonlinear sampled peak(Hz) | Min compute(MW/port) | V range(pu) | Frequency result |','|---|---:|---:|---:|---:|---:|---:|---|']
for r in rows:
 md.append(f"| {r['label']} | {r['dt_s']:.8f} | {r['total_deltaP_capacity_MW']:.6f} | {r['exact_LTI_peak_Hz']:.8f} | {r['sampled_nonlinear_peak_Hz']:.8f} | {r['min_computeP_MW']:.6f} | {r['min_busV_pu']:.6f}–{r['max_busV_pu']:.6f} | {r['finite_case_frequency_status']}0.05Hz |")
md+=['','Fine-step comparison (same inputs and full histories):']
for r in s['refinements']:md.append(f"- {r['label']}: coarse/fine sampled peaks {r['coarse_peak_Hz']:.9f}/{r['fine_peak_Hz']:.9f}Hz; absolute difference {r['absolute_peak_change_Hz']:.3g}Hz; same finite frequency classification={r['classifications_same']}")
cs=json.loads((P/'POSITIVE_NONLINEAR_CASES.json').read_text());reset=next(c for c in cs['cases'] if c['label']=='reset_false_admission');fine=next(r for r in rows if r['label']=='reset_false_admission_dt256');md+=['',f"At the physically capped98MW reset-error case, the invalid reset screen predicts at most{reset['reset_screen_upper_Hz']:.8f}Hz, while the carried-state finite nonlinear witness reaches{fine['sampled_nonlinear_peak_Hz']:.8f}Hz at fine step. Actual compute power remains >=1MW each. Thus the false-admission example does not rely on negative compute load. The associated proper common-contract LTI envelope is{reset['proper_contract_upper_Hz']:.8f}Hz, correctly rejecting this amplitude.",'','Every case has exactly50MW mean compute demand per port and zero incremental energy per full block. Under the explicit affine law only, each block delivers2*wbar_i work and the complete514s forcing word514*wbar_i. POSITIVE_NONLINEAR_TABLE.csv includes the full requested-input/work/frequency/voltage ledger.','', 'These finite numerical checks support boundary interpretation only for the selected words at this one nominal point. They do not validate every nonlinear word, all physical operating constraints, or actual compute throughput. In particular, observed low voltages rule out interpreting the frequency-only result as full grid hosting certification.']
p=P/'POSITIVE_WORKPOINT_REPORT.md';txt=p.read_text();old='Results will be appended after all predeclared runs complete. Replayed traces establish only those finite cases, not all words in a nonlinear contract family. Timestep convergence supports numerical reliability but is not a continuous-time nonlinear proof.';assert old in txt,'Avoid duplicate finalization';txt=txt.replace(old,'\n'.join(md));txt=txt.replace('its final status remains pending the complete nonlinear package.', 'consult that audit for independent verification of the complete nonlinear package.');p.write_text(txt)
individual=[json.loads((P/(d['label']+'.json')).read_text()) for d in s['results']]
assert len({d['initial_x_sha256'] for d in individual})==1 and len({d['initial_y_sha256'] for d in individual})==1
qual=json.loads((P/'QUALIFICATION.json').read_text());support=json.loads((P/'positive_summary.json').read_text());freeze=json.loads((P/'POSITIVE_WORKPOINT_FREEZE.json').read_text())
old_model=np.load(P.parents[1]/'round2_20261003/grid_transfer/kundur_reduced51.npz');source_checks={'old_A_unchanged':hashlib.sha256(old_model['A'].tobytes()).hexdigest()==qual['changed_model_check']['old_A_sha256'],'original_grid_adapter_unchanged':hashlib.sha256((P.parents[1]/'round2_20261003/grid_transfer/grid_adapter.py').read_bytes()).hexdigest()==freeze['copied_grid_adapter_sha256'],'support_implementation_unchanged':hashlib.sha256((P.parent/'transfer/run_transfer.py').read_bytes()).hexdigest()==support['qualification']['source_support_script_sha256'],'nonlinear_input_kernel_unchanged':all(hashlib.sha256((P/n).read_bytes()).hexdigest()==v for n,v in cs['support_inputs_hashes'].items()),'all10_identical_initial_states':True}
assert all(source_checks.values())
(P/'SOURCE_AND_INITIAL_STATE_INTEGRITY.json').write_text(json.dumps(source_checks,indent=2))
inputs=[P.parent/'transfer/run_transfer.py',P.parent/'nonlinear/run_g6_nonlinear.py',P.parents[1]/'round2_20261003/grid_transfer/grid_adapter.py',P.parents[1]/'round2_20261003/grid_transfer/kundur_reduced51.npz']
manifest={'finalized_utc':datetime.datetime.now(datetime.timezone.utc).isoformat(),'source_inputs':{str(f):hashlib.sha256(f.read_bytes()).hexdigest() for f in inputs},'all_predeclared_cases_complete':True,'output_files':{str(f.relative_to(P)):hashlib.sha256(f.read_bytes()).hexdigest() for f in P.iterdir() if f.is_file() and f.name!='POSITIVE_ARTIFACT_MANIFEST.json'}}
(P/'POSITIVE_ARTIFACT_MANIFEST.json').write_text(json.dumps(manifest,indent=2));print('FINALIZED',len(rows),'cases')
