from pathlib import Path
import json,hashlib,datetime
ROOT=Path(__file__).resolve().parents[1]
p=ROOT/'protocol/GATE_A_LOCKED_V2_1.json'
cases=[]
for ps,qs,name in [(1,1,'pp'),(1,-1,'pn'),(-1,1,'np'),(-1,-1,'nn')]:
 cases.append(dict(id='steady_'+name,kind='steady',P_W=ps*300000.,Q_var=qs*200000.,purpose='Finite-time four-quadrant averaged-converter equilibrium and energy drift check'))
for ps,qs,name in [(1,1,'pp'),(1,-1,'pn'),(-1,1,'np'),(-1,-1,'nn')]:
 cases.append(dict(id='step_'+name,kind='step',checkpoint_case='steady_'+name,P0_W=ps*300000.,Q0_var=qs*200000.,P1_W=ps*350000.,Q1_var=qs*225000.,event_after_checkpoint_s=.00005,purpose='Outward same-quadrant small simultaneous P/Q request step'))
for name,a in [('sag085',.85),('sag075',.75),('sag0475',.475)]:
 cases.append(dict(id=name,kind='sag',checkpoint='gate_a/preconditioned_dq/h1e-05_checkpoint.json',P_W=800000.,Q_var=700000.,event_after_checkpoint_s=.00005,retained_source_voltage_pu=a,duration_s=.15,purpose='Prespecified remote-source/RL necessary-energy-margin point; not certified feasible'))
cases.append(dict(id='signed_periodic',kind='periodic',P_amplitude_W=300000.,frequency_Hz=1.,Q_var=0.,initial_bias_W=0.,bias_bounds_W=[-50000.,0.],initial_sine_phase_rad=0.,calibration_max_cycles=12,confirmation_max_cycles=8,qualifying_cycles=3,bias_update='At each completed calibration cycle, b_next=clip(b_current+delta_stored_battery_energy_J/period_s,-50000,0). Uses only past full-cycle energy; freeze at first 3 consecutive qualifying cycles or after 12 calibration cycles, then confirm at least 3 whole cycles.',bias_causal_availability='Requires exact simulated stored-energy change and a known periodic forcing clock. It is an instrumented existence/calibration check, not a validated noisy BMS estimator or novel service controller.',stored_energy_cycle_tolerance_J=1.,purpose='Loss-compensated signed periodic target-orbit existence check; negative mean PCC power supplies losses'))
d=dict(schema='G3 Gate A extension v1',frozen_utc=datetime.datetime.now(datetime.timezone.utc).isoformat(),authorization='Parent approved 12-condition Gate A model diagnostics on 2026-10-02; no Gate B controller or performance search',base_protocol=str(p.relative_to(ROOT)),base_protocol_sha256=hashlib.sha256(p.read_bytes()).hexdigest(),physical_parameters_and_control_law='Unchanged V2.1 resources, GFL averaged topology, Q-priority inverse-current clipping, PI/PLL/DC source law, 100 us sample clock and one-sample normalized-modulation delay. No state projection.',cases=cases,
 steady_rule=dict(compare_period_s=.05,full_state_normalized_tolerance=1e-5,successive_checks=3,max_prerun_s=5.,hard_safe_window_s=.15,frequency_deviation_Hz=.001,energy_exclusion='Battery inventory and cumulative energy integrals are excluded from electrical orbit convergence but recorded with their known finite-discharge or charge trend and SoC hard bounds.'),
 recovery_rule=dict(max_after_event_or_clearance_s=2.,compare_period_s=.05,successive_checks=3,full_state_normalized_tolerance=1e-5,hard_safe_window_s=.15,frequency_deviation_Hz=.001,sag_target='Full normalized pre-fault checkpoint state at every sample, in nominal source frame; compare the converged pre-fault cycle template if needed. Battery energy/cumulative integrals excluded but accounted.',step_target='Converged new finite operating state: full state cycles separated by 50 ms, same rule; not old P/Q setpoint.',limiter_release='All current-reference allocation, modulation, battery-source-command clipping and PLL frequency clipping absent throughout final 150 ms. Report last active sample and release delay.',success='Report separately: complete simulation; all post-checkpoint hard limits safe; restored electrical/controller state; limiter release. Complete safe recovery requires all.'),
 hard_limits=dict(actual_current_pu=1.,P_pcc_abs_W=950000.,S_pcc_VA=1200000.,dc_pu=[.8,1.1],P_battery_terminal_abs_W=1000000.,soc=[.2,.8],modulation_norm_max=.95/(3**.5),emergency_current_pu=1.1,comparison_roundoff_tolerance=1e-8),
 periodic_rule=dict(period_s=1.,compare='Every sample state against same-phase sample in preceding full 1 s cycle; includes current, DC energy, battery terminal/source command, PLL angle relative to source, integrators, applied/queued modulation and held frequency.',full_state_normalized_tolerance=1e-5,max_forcing_time_s=20.,confirmation_success='3 consecutive full cycles after bias frozen, each full-state cycle difference <=1e-5 and |stored battery energy delta|<=1 J, hard safe, and all limiters inactive; retain bias and all calibration history.',prewarm='First safe converged b=0,Q=0 finite equilibrium under common 50ms rule, max5s, then sine starts at phase0 on its controller-clock checkpoint.',pll_periodic_rule='No instantaneous 1 mHz nominal-frequency requirement during ongoing signed forcing; require bounded frequency, periodic full PLL state, and zero mean PLL frequency drift within1mHz over final cycle.',limits_of_claim='Finite numerical evidence for a repeating loss-compensated averaged-model orbit, not a proof of infinite-time invariance or a field calibration.'),
 numerical=dict(primary='DOP853 nominal dq; rtol1e-10 atol1e-8; exact control/event boundaries',control_sample_s=.0001,max_step_s=.00001,boundary_refinement_s=.000005,refine_cases=['sag0475'],adaptive_refinement_rule='Any new case within 0.001 pu actual-current or DC hard boundary, or within0.001 relative AC S/P hard boundary, is repeated at5us under identical conditions; counted as numerical refinement, not new condition.',abc_cases=['sag085','sag0475'],abc_steps_s={'sag085':[.00001],'sag0475':[.00001,.000005]},event_checks='Actual-current crossings, emergency1.1pu, Vdc bounds and SoC bounds. Record all safety breaches; emergency/DC/SoC crossings terminate.'),
 storage=dict(ordinary='Compressed100us endpoint plant/controller/normalized-state traces plus each interval internal-solver extrema, safety and saturation bits, convergence log and full checkpoint. No duplicate dense ordinary5us trace unless boundary rule triggers.',sag='Retain all primary10us internal trajectory rows and full100us state/control records for all three sag conditions; retain5us raw sag0475, and same independentabc representative records.',periodic='Preserve all100us endpoint/full-state records and per-interval extrema for calibration+confirmation, all bias/cycle energy logs, final full plant/controller checkpoint; no routine5us duplicate.',provenance='New experiment, not restored historical evidence. Append new files only; preserve complete prior archive and its hashes.'),
 boundary_selection=dict(source='protocol/gate_a_extension_boundary_selection.json',rule='150ms sag; low-conflict retained0.85 and0.75 plus rounded-up near-boundary0.475, selected from source/RL all-strategy necessary-energy certificate before dynamic extension runs.',critical_retained_voltage_pu_approx=.47419213725,near_boundary_available_minus_required_J_approx=40.506,interpretation='Positive necessary margin means this particular necessary inequality does not exclude feasibility. It is not an inner feasible-set certificate.'))
f=ROOT/'protocol/GATE_A_EXTENSION_V1.json';f.write_text(json.dumps(d,indent=2,ensure_ascii=False)+'\n');h=hashlib.sha256(f.read_bytes()).hexdigest();f.with_suffix('.sha256').write_text(h+'  '+f.name+'\n');print(h)
