from pathlib import Path
import json,hashlib
import numpy as np
import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt
R=Path(__file__).resolve().parent;OLD=R.parent/'recovery_phase2'/'V2'
x=json.loads((R/'SUMMARY_PHASE3.json').read_text());cs=x['cases'];fine=[c for c in cs if c['dt_s']==.5e-6];nom=fine[0]
D={b:np.load((R if b=='L' else OLD)/('nominal_h05'+{'S':'_s1','F':'_s0','L':'_L'}[b]+'.npz')) for b in ['F','L','S']};cols={'F':'gray','L':'tab:orange','S':'tab:blue'};labels={'F':'F: flat-load baseline','L':'L: same workload, load-following','S':'S: same workload, grid service'}
fig,ax=plt.subplots(3,1,figsize=(10,9),sharex=True)
for b,z in D.items():
 t=z['t']-2;m=t<=.22
 ax[0].plot(t[m],z['loadmean'][m]/1000,label=labels[b],color=cols[b],lw=2 if b=='L' else 1,ls='--' if b=='S' else '-')
 ax[1].plot(t[m],z['Pmean'][m]/1000,label=labels[b],color=cols[b],lw=1)
 ax[2].plot(t[m],(z['load_energy'][m]-D['F']['load_energy'][m])/1000,label=labels[b],color=cols[b],lw=2 if b=='L' else 1,ls='--' if b=='S' else '-')
for a in ax:a.grid(alpha=.25);a.axvline(.2,color='black',ls=':')
ax[0].legend(fontsize=9);ax[0].set_ylabel('Actual compute input (kW)');ax[1].set_ylabel('Actual grid P, PWM mean (kW)');ax[2].set_ylabel('Cumulative task energy − F (kJ)');ax[2].set_xlabel('Time since nominal onset (s)');fig.suptitle('Same time-resolved workload: S and L agree; flat reference F does not');fig.tight_layout();fig.savefig(R/'THREE_BRANCH_WORKLOAD_AND_POWER.png',dpi=170);plt.close(fig)
fig,ax=plt.subplots(2,1,figsize=(10,7));t=D['S']['t']-2
for p,a,b,col in [('S−F','S','F','tab:blue'),('L−F','L','F','tab:orange'),('S−L','S','L','tab:green')]:ax[0].plot(t,(D[a]['grid_energy']-D[b]['grid_energy'])/1000,label=p,color=col)
ax[0].axvline(.2,color='black',ls=':');ax[0].axvline(.7,color='black',ls='--');ax[0].legend();ax[0].grid(alpha=.25);ax[0].set_xlabel('Time since nominal onset (s)');ax[0].set_ylabel('Cumulative grid increment (kJ)')
pairs=['S-F','S-L','L-F'];pos=np.arange(3);values=[[nom['ledger']['recovery']['paired_increments'][p][k] for p in pairs] for k in ['grid_energy_J','positive_grid_energy_J','absolute_integral_grid_energy_J']]
for off,val,label in zip([-.25,0,.25],values,['Signed','Positive-only','Absolute integral']):ax[1].bar(pos+off,val,width=.25,label=label)
ax[1].set_xticks(pos,pairs);ax[1].set_ylabel('Recovery energy increment (J)');ax[1].legend();ax[1].grid(axis='y',alpha=.25);fig.suptitle('Signed increments decompose; positive and absolute costs are evaluated directly');fig.tight_layout();fig.savefig(R/'THREE_BRANCH_ENERGY_ATTRIBUTION.png',dpi=170);plt.close(fig)
mx=lambda f:max(f(c) for c in cs)
lines=['# Phase3: time-resolved workload-matched counterfactual','', '## Result and corrected scope',f"All {len(cs)} retrospective comparator checks pass the newly declared S−L finite-contract tests. These are the 17 already evaluated V2 physical/clock configurations at two integration resolutions. No new blind confirmation is claimed.",'',
'The previous V2 no-service branch removed the compute pulses as well as requested grid service. Its correct label is the flat-load baseline F. It remains valid for baseline-orbit recovery: during the recovery interval [0.2,0.7] s, F and S both already consume 650 kW, but their entering physical/controller states contain different service histories. Those old return costs are not isolated whole-service attribution at equal time-resolved workload. All old results and freezes remain intact.','',
'This stage adds L, a feasible load-following no-grid-service comparator that receives exactly the same actual compute input d(t) as S at every time. S−L is the service-strategy increment relative to this explicitly chosen feasible load-following policy under identical time-resolved compute input. It is not the globally optimal no-service opportunity cost, a unique universal causal allocation, or a new proof of uniform uncertainty robustness.','',
'## Exact branch definitions and source locations','- F: existing V2 mode0, Pbaseline=654498.72485653043 W, Q=0, d=650000 W, uFeed=0, with the same service-clock freeze/resume gates','- S: existing V2 mode1, original prescribed P/Q/d/uFeed service schedule and unchanged V2 recovery controller','- L: new mode2, dL(t)=dS(t), Qrequest=0, uFeed=0, and Prequest=(1−sqrt(1−4cd))/(2c), c=R/(1.5VP²), using fixed nominal R=0.005 ohm and VP=563.3826408401309 V. The implementation evaluates the algebraically identical stable form 2d/(1+sqrt(1−4cd)); Pdot=d_dot/sqrt(1−4cd)','',
'In rectifier_load_match.cpp, lines31–32 derive d_dot from the same authorized piecewise-linear workload schedule; lines43–49 define F/S/L, with line46 preserving the original S command path and lines47–48 preserving d in slot2 while changing only L P/Q/uFeed. Lines51–55 consume that same d slot in the physical DC equation. Lines72–74 retain V2 gating and capacitor-plus-inventory PI; lines75–77 retain current control and the authorized midpoint preview. Actual tau/ramp are used only in the physical battery-port equation at line55.','',
'One immutable V2 nominal warmup checkpoint per integration step initializes all corresponding branches. The absolute grid/carrier clock, service onset and sampling are unchanged. Known-schedule half-period P/Q prediction is permitted as before; no future measured workload or matched-health signal is read. Pre-onset differences caused by known preview are included in their own ledger and in checkpoint-to-final totals; onset states are not assumed identical. No workload is curtailed, shifted or reallocated.','',
'## Exact workload and service-window accounting','The input CSV extends to0.3 s; integrating that entire file gives195 kJ. The actual service ends at0.2 s and has130 kJ of compute input, identical in cumulative total to flat650kW over0.2 s. These two intervals must not be confused. S and F differ at intermediate times: their cumulative task-energy difference peaks at10.5 kJ despite returning to zero at the service endpoint. S and L use the identical input function throughout, not merely the same total energy.','',
 f"Across all runs, maximum numerical S/L cumulative load-energy discrepancy is {mx(lambda c:c['max_cumulative_S_L_load_energy_difference_J']):.9g} J, below the frozen1e−5 J check. This is integration residual from different switching subgrids; exact function equality follows from the common interpolation expression, not a requirement that independently accumulated floating-point integrals be bitwise equal.",'',
'Both new-executable nominal S replays reproduce the old S main/snapshot/bin CSV files byte-for-byte, all dense arrays bitwise, and every reported extremum exactly. SERVICE_REPLAY_IDENTITY.json records these checks. All other S/F data are reused read-only.','',
'## Frozen comparison contract','PROTOCOL_PHASE3.json, executable, runner, evaluation script, original input and checkpoint copies were hashed before the first new simulation in EXECUTION_FREEZE_PHASE3.json. Both implementation and independent-audit evaluators were fixed before seeing L results.','',
'- Physical bounds for S and L: voltage1080–1320 V, each phase and space-vector current≤1500 A, B0–100 kJ, |b|/|u|≤450 kW, declared physical slew, PWM and circular utilization≤1','- Service tracking against each branch’s own request: ten matching20ms-window means, P error≤2 kW and Q error≤10 kvar','- Return: in the final five20ms cycles ending atT+0.5 s, common1us samples satisfy |WS−WL|/|BS−BL|≤2 J and each paired phase-current difference≤2 A','- Recovery budget fromT toT+0.5 s: paired cP≤5 kW; absolute net signed, positive-only and absolute-integral grid increments each≤100 J','- Continuing observation extends toT+0.7 s. All six windows retain individual branch energies, paired increments and ΔW/ΔB/ΔZ','',
'These are new comparator-stage tests of the original V2 trajectory against L. They do not retroactively change V2, extend the recovery100J budget to whole-service absolute throughput, or validate the distinct core exact-return100J contract.','',
'## Results',f"Worst S−L return differences across all34 runs: W={mx(lambda c:c['dense_final100ms_differences']['S-L']['W']):.9g} J, B={mx(lambda c:c['dense_final100ms_differences']['S-L']['B']):.9g} J, phase current={mx(lambda c:max(c['dense_final100ms_differences']['S-L'][k] for k in ['ia','ib','ic'])):.9g} A.",f"Worst S−L recovery costs: |signed|={mx(lambda c:abs(c['ledger']['recovery']['paired_increments']['S-L']['grid_energy_J'])):.9g} J, positive-only={mx(lambda c:c['ledger']['recovery']['paired_increments']['S-L']['positive_grid_energy_J']):.9g} J, absolute integral={mx(lambda c:c['ledger']['recovery']['paired_increments']['S-L']['absolute_integral_grid_energy_J']):.9g} J, paired cP={mx(lambda c:c['ledger']['recovery']['paired_increments']['S-L']['max_abs_incremental_cP_W']):.9g} W.",f"L is physically feasible in every check: V={min(c['extrema']['L']['all']['Vmin'] for c in cs):.6f}–{mx(lambda c:c['extrema']['L']['all']['Vmax']):.6f} V; peak absolute phase current={mx(lambda c:c['extrema']['L']['all']['Iphase']):.6f} A; peak space-vector amplitude={mx(lambda c:c['extrema']['L']['all']['Ispace']):.6f} A; maximum circular modulation={mx(lambda c:c['extrema']['L']['all']['circular']):.9f}. The observed L battery state remains at its initial inventory because its port feedforward and inventory error are zero; this does not turn it into a constant-import comparator.",'',
'Fine-step matrix:', '', '| Case | S−L max W J | max B J | max phase A | recovery signed J | positive J | absolute J | paired cP W | pass |','|---|---:|---:|---:|---:|---:|---:|---:|---|']
for c in fine:
 d=c['dense_final100ms_differences']['S-L'];e=c['ledger']['recovery']['paired_increments']['S-L'];lines.append(f"| {c['tag']} | {d['W']:.6g} | {d['B']:.6g} | {max(d[k] for k in ['ia','ib','ic']):.6g} | {e['grid_energy_J']:.6g} | {e['positive_grid_energy_J']:.6g} | {e['absolute_integral_grid_energy_J']:.6g} | {e['max_abs_incremental_cP_W']:.6g} | {c['pass']} |")
lines+=['','## Three-branch energy attribution','For every signed window and every additive ledger component, S−F=(S−L)+(L−F). This is an exact algebraic decomposition of specified trajectories. It is not a corresponding identity for positive-only or absolute-integral costs. Those nonlinear costs are recomputed directly from each paired PWM-cycle mean waveform. Signed grid energies use exact integration boundary snapshots.','',f"Maximum computed signed-triangle residual across all34 cases and six windows is {mx(lambda c:c['signed_triangle_residual_max_J']):.9g} J. The complete table has individual F/L/S gross grid, copper, load, bridge and stored-energy ledgers plus all three paired signed/nonlinear costs.",'',
'Nominal fine-step signed gross AC decomposition:', '', '| Window | S−F J | S−L J | L−F J |','|---|---:|---:|---:|']
for w in ['pre_onset','service','recovery','post_deadline','declared_onset_total','checkpoint_total']:
 a=nom['ledger'][w]['paired_increments'];lines.append(f"| {w} | {a['S-F']['grid_energy_J']:.9f} | {a['S-L']['grid_energy_J']:.9f} | {a['L-F']['grid_energy_J']:.9f} |")
lines+=['','Nominal fine-step recovery costs:', '', '| Pair | signed J | positive-only J | absolute integral J |','|---|---:|---:|---:|']
for pair in ['S-F','S-L','L-F']:
 a=nom['ledger']['recovery']['paired_increments'][pair];lines.append(f"| {pair} | {a['grid_energy_J']:.9f} | {a['positive_grid_energy_J']:.9f} | {a['absolute_integral_grid_energy_J']:.9f} |")
lines+=['','The whole-task positive/absolute integrals are much larger than the return-window metrics because S and L intentionally use different grid-power waveforms during service. For nominal S−L, the full checkpoint-to-final signed AC increment is69.002737 J, while positive-only energy is14248.770799 J and the absolute integral is28428.538862 J. No100J whole-task absolute-throughput claim is made.','',
'The full nominal S−L signed grid increment is almost entirely extra copper loss: grid69.002736744 J versus copper69.002740913 J, leaving net-after-copper≈−4.17e−6 J and effectively equal final stored energy at the numerical resolution. This supplies the requested attribution relative to L without hiding reactive-current or load-shape copper losses. All ΔZ terms remain explicit; the controller still regulates W+B, not W+B+Z.','',
'## Preservation, limitations and files',f"The preservation check covers {x['prior_files_checked']} existing files, including all earlier recovery artifacts and both root/public-core copies of FINAL_SCIENTIFIC_STATUS.json and RECOVERY_COMPLETE_MANIFEST.json; none changed.",
'Physical conclusions remain limited to the declared ideal switching plant, prescribed balanced grid, nominal known R/L/C, ideal sampled measurements, actual tested port tau/ramp, and one workload/service witness. Two integration steps demonstrate numerical consistency, not measurement accuracy. L is a deliberately strong feasible reference, not an optimized universal no-service policy.','',
'- SUMMARY_PHASE3.json: complete branch/pair states, extrema, convergence, acceptance and signed identities','- ACCEPTANCE_PHASE3.csv: all34 row classifications','- ENERGY_ATTRIBUTION_PHASE3.csv: all six windows, F/L/S absolute ledgers and S−L/L−F/S−F paired increments','- SERVICE_REPLAY_IDENTITY.json: old-S exact replay proof','- PROTOCOL_PHASE3.json and EXECUTION_FREEZE_PHASE3.json: pre-result definitions, configuration set and hashes','- audit/: independent source/workload/energy/comparator assessment, without importing the implementation evaluator','- THREE_BRANCH_WORKLOAD_AND_POWER.png and THREE_BRANCH_ENERGY_ATTRIBUTION.png: visual branch comparison','',
'No prior freeze is replaced. A separate PHASE3_INDEX/manifest provides the new stage’s stable entry point.']
(R/'REPORT_PHASE3.md').write_text('\n'.join(lines)+'\n');print('Report and two figures created')
